// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_middleware.ts';
import * as $1 from './routes/api/joke.ts';
import * as $2 from './routes/game/[id]/admin.tsx';
import * as $3 from './routes/index.tsx';
import * as $4 from './routes/login.tsx';
import * as $$0 from './islands/Chat.tsx';
import * as $$1 from './islands/Counter.tsx';
import * as $$2 from './islands/NewGameForm.tsx';
import * as $$3 from './islands/OfflineMode.tsx';
import * as $$4 from './islands/ResetGame.tsx';
import * as $$5 from './islands/SurfaceView.tsx';

const manifest = {
  routes: {
    './routes/_middleware.ts': $0,
    './routes/api/joke.ts': $1,
    './routes/game/[id]/admin.tsx': $2,
    './routes/index.tsx': $3,
    './routes/login.tsx': $4,
  },
  islands: {
    './islands/Chat.tsx': $$0,
    './islands/Counter.tsx': $$1,
    './islands/NewGameForm.tsx': $$2,
    './islands/OfflineMode.tsx': $$3,
    './islands/ResetGame.tsx': $$4,
    './islands/SurfaceView.tsx': $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
